name: Unit Tests

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  phpunit:
    name: PHPUnit
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Run unit tests
        run: make test
